<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\kn24_php\kn24_php\src\Classes\..\templates\aboutme.latte */
final class Template_eaaa99c9dd extends Latte\Runtime\Template
{
	public const Source = 'C:\\Users\\User\\Desktop\\kn24_php\\kn24_php\\src\\Classes\\..\\templates\\aboutme.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="aboutme" style="padding:2rem; text-align:center;">
    <h1>';
		echo LR\Filters::escapeHtmlText($title) /* line 2 */;
		echo '</h1>
    <p><strong>Ім’я:</strong> ';
		echo LR\Filters::escapeHtmlText($name) /* line 3 */;
		echo '</p>
    <p>';
		echo LR\Filters::escapeHtmlText($description) /* line 4 */;
		echo '</p>

    <h3>Мої навички:</h3>
    <ul style="list-style:none; padding:0;">
';
		foreach ($skills as $skill) /* line 8 */ {
			echo '            <li>';
			echo LR\Filters::escapeHtmlText($skill) /* line 9 */;
			echo '</li>
';

		}

		echo '    </ul>
</section>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['skill' => '8'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
