<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\kn24_php\kn24_php\src\Classes\..\templates\error404.latte */
final class Template_f448a63223 extends Latte\Runtime\Template
{
	public const Source = 'C:\\Users\\User\\Desktop\\kn24_php\\kn24_php\\src\\Classes\\..\\templates\\error404.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<h2>Помилка 404</h2>
<p>';
		echo LR\Filters::escapeHtmlText($message) /* line 2 */;
		echo '</p>
<p><a href="/">Повернутися на головну</a></p>';
	}
}
