<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\kn24_php\kn24_php\src\Classes\..\templates\game.latte */
final class Template_de8fe77f55 extends Latte\Runtime\Template
{
	public const Source = 'C:\\Users\\User\\Desktop\\kn24_php\\kn24_php\\src\\Classes\\..\\templates\\game.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<h1>Це у нас сторінка гри (файл src/templates/game.latte)</h1>

';
		if ($gamesList) /* line 3 */ {
			echo '<ul>
';
			foreach ($gamesList as $game) /* line 4 */ {
				echo '    <li>
        ';
				echo LR\Filters::escapeHtmlText($game['id']) /* line 6 */;
				echo ' - ';
				echo LR\Filters::escapeHtmlText($game['title']) /* line 6 */;
				echo ' - ';
				echo LR\Filters::escapeHtmlText($game['description']) /* line 6 */;
				echo ' 
    </li>
';

			}

			echo '</ul>
';
		}
		echo '
<form method="POST" action="/game">
    <input type="text" name="title" placeholder="title" required/>
    <input type="text" name="description" placeholder="description" required/>
        
    <button type="submit" class="btn-success">
        Додати в базу
    </button>
</form>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['game' => '4'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
